spring:
  application:
    name: banking-api
  datasource:
    url: jdbc:mysql://localhost:3306/bankingsystem
    username: root
    password: shubham
    driver-class-name: com.mysql.cj.jdbc.Driver
    auto-index-creation: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update


